Repository Embucket/embucket, pull requests merged in 2025-05, with the labels that each got.

#703 Reasonable default for cli options
  .env.example
  bin/bucketd/src/cli.rs
Labels: deploy

#724 Utoipa Spec Fixes for tables & auth
  crates/runtime/src/http/auth/handlers.rs
  crates/runtime/src/http/auth/models.rs
  crates/runtime/src/http/ui/dashboard/handlers.rs
  crates/runtime/src/http/ui/databases/handlers.rs
  crates/runtime/src/http/ui/navigation_trees/handlers.rs
  crates/runtime/src/http/ui/queries/handlers.rs
  crates/runtime/src/http/ui/router.rs
  crates/runtime/src/http/ui/schemas/handlers.rs
  crates/runtime/src/http/ui/tables/handlers.rs
  crates/runtime/src/http/ui/volumes/handlers.rs
  crates/runtime/src/http/ui/worksheets/handlers.rs
Labels: deploy

#759 Expired session must be deleted (part of leak #435)
  crates/api-sessions/src/session.rs
  crates/core-executor/src/service.rs
Labels: deploy

#778 refactor: update SLT runner API usage for schema and db management
  test/slt_runner/python_runner.py
Labels: dbt

#805 api: UI Create & Delete Volumes handler `utoipa` schema fix
  crates/api-ui/src/volumes/handlers.rs
Labels: deploy

#818 feat: add SLT generator folder with scripts for SQL Logic Tests gener…
  test/slt_generator/.env_example
  test/slt_generator/README.md
  test/slt_generator/enrich_queries_with_llm.py
  test/slt_generator/html_to_queries.py
  test/slt_generator/queries_to_slt.py
  test/slt_generator/reference_iterator.py
  test/slt_generator/reference_to_html.py
Labels: dbt

#831 Schemas DF View Store (SlateDb)
  crates/core-metastore/src/metastore.rs
  crates/df-catalog/src/catalogs/slatedb/config.rs
  crates/df-catalog/src/catalogs/slatedb/mod.rs
  crates/df-catalog/src/catalogs/slatedb/schema.rs
  crates/df-catalog/src/catalogs/slatedb/schemas.rs
Labels: deploy

#835 Tables DF View Store (SlateDb)
  crates/core-metastore/src/metastore.rs
  crates/core-metastore/src/models/schema.rs
  crates/core-metastore/src/models/table.rs
  crates/df-catalog/src/catalogs/slatedb/config.rs
  crates/df-catalog/src/catalogs/slatedb/mod.rs
  crates/df-catalog/src/catalogs/slatedb/schema.rs
  crates/df-catalog/src/catalogs/slatedb/tables.rs
Labels: deploy

#839 Schemas and Databases search through the query engine
  Cargo.lock
  crates/api-ui/src/databases/error.rs
  crates/api-ui/src/databases/handlers.rs
  crates/api-ui/src/databases/models.rs
  crates/api-ui/src/lib.rs
  crates/api-ui/src/navigation_trees/handlers.rs
  crates/api-ui/src/schemas/error.rs
  crates/api-ui/src/schemas/handlers.rs
  crates/api-ui/src/schemas/models.rs
  crates/api-ui/src/tests/dashboard.rs
  crates/api-ui/src/tests/databases.rs
  crates/api-ui/src/tests/schemas.rs
  crates/df-catalog/src/catalogs/slatedb/config.rs
  crates/df-catalog/src/catalogs/slatedb/databases.rs
  crates/df-catalog/src/catalogs/slatedb/tables.rs
  crates/df-catalog/src/catalogs/slatedb/volumes.rs
Labels: deploy

#883 fix: update retry logic, remove unused method
  test/slt_runner/result.py
Labels: testsuite

#894 feat: add parallel execution option for SQL logic tests, update readme
  test/README.md
  test/slt_runner/python_runner.py
Labels: testsuite

#941 feat: refactor setup and configuration loading for Embucket run
  test/slt_runner/python_runner.py
Labels: testsuite

#966 Improve slt comments
  test/slt_runner_targeted.py
  test/slt_selector.py
Labels: github_actions, testsuite
