Repository Embucket/embucket, pull requests merged in 2025-07, with the labels that each got.

#1252 fix: populate metadata_location field in iceberg REST API responses
  crates/api-iceberg-rest/src/handlers.rs
Labels: iceberg

#1293 feat: update github workflow SLT action with new user credentials and…
  .github/workflows/slt-targeted-testing.yml
  .github/workflows/sql-logic-tests.yml
Labels: github_actions, testsuite

#1324 Add script to combine historical SLT results and upload to Embucket, …
  .github/workflows/sql-logic-tests.yml
  test/combine_historical_slt_results_and_upload_to_embucket.py
Labels: testsuite

#1375 CI: Add DATABASE and SCHEMA environment variables to SLT results uplo…
  .github/workflows/sql-logic-tests.yml
Labels: testsuite

#1382 CI: Update EMBUCKET_HOST to dp.embucket.com in SLT results upload job
  .github/workflows/sql-logic-tests.yml
Labels: testsuite
